services:
  - type: web
    name: pdf-generator-service
    env: python
    plan: free

    build:
      pythonVersion: 3.10.12

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
