services:
  - type: web
    name: pdf-generator-service
    env: python
    plan: free
    runtime: python3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT